<a href="https://colab.research.google.com/github/Mz22222/PythonSeminars/blob/master/Sem_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание_1


1)Прочесть с помощью pandas файл california_housing_test.csv, который находится в папке sample_data


2)Посмотреть сколько в нем строк и столбцов


3) Определить какой тип данных имеют столбцы

In [49]:
import pandas

In [50]:
df = pandas.read_csv('/content/sample_data/california_housing_test.csv')

In [51]:
df.head(n = 15)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0
10,-118.24,33.98,45.0,972.0,249.0,1288.0,261.0,2.2054,125000.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
12,-121.93,37.25,36.0,1089.0,182.0,535.0,170.0,4.6900,252600.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
14,-117.97,33.73,27.0,2097.0,325.0,1217.0,331.0,5.7121,222500.0

In [52]:
df.shape

(3000, 9)

In [53]:
df.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
dtype: object

Задание_2

1) Проверить есть ли в файле пустые значения


2) Показать median_house_value где median_income < 2


3) Показать данные в первых 2 столбцах


4) Выбрать данные где housing_median_age < 20 и median_house_value > 7000

In [54]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [55]:
len(df[df['median_income']<2]['median_house_value'])

360

In [56]:
df[:2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0

In [57]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [58]:
for i in df.columns [1:3]:
  print(df[i])

0       37.37
1       34.26
2       33.78
3       33.82
4       36.33
        ...
2995    34.42
2996    34.06
2997    36.30
2998    34.10
2999    34.42
Name: latitude, Length: 3000, dtype: float64
0       27.0
1       43.0
2       27.0
3       28.0
4       19.0
        ...
2995    23.0
2996    27.0
2997    10.0
2998    40.0
2999    42.0
Name: housing_median_age, Length: 3000, dtype: float64

In [59]:
df[(df['housing_median_age']<20) & (df['median_house_value'] > 7000)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
13,-117.03,32.97,16.0,3936.0,694.0,1935.0,659.0,4.5625,231200.0
16,-120.81,37.53,15.0,570.0,123.0,189.0,107.0,1.8750,181300.0
...,...,...,...,...,...,...,...,...,...
2981,-120.66,35.49,17.0,4422.0,945.0,2307.0,885.0,2.8285,171300.0
2984,-117.59,33.88,13.0,3239.0,849.0,2751.0,813.0,2.6111,107000.0
2985,-120.47,34.94,17.0,1368.0,308.0,642.0,303.0,1.8633,109400.0
2991,-117.17,34.28,13.0,4867.0,718.0,780.0,250.0,7.1997,253800.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0

Задание_3

1) Определить какое максимальное и минимальное значение median_house_value

2) Показать максимальное median_house_value, где median_income = 3.1250

3) Узнать какая максимальная population в зоне минимального значения median_house_value

In [60]:
df['median_house_value'].max(), df['median_house_value'].min()

(500001.0, 22500.0)

In [63]:
df[df['median_income'] == 3.1250]['median_house_value'].max()

233300.0

In [67]:
df[df['median_house_value'] == df['median_house_value'].min()]['population'].max()

1230.0